version: '3.9'
services:
  app:
    image: phinixhq/bitcoinish-fullnode-exporter
    restart: unless-stopped
    environment: 
      REFRESH_INTERVAL_MILLISECONDS: "60000"
      AXIOS_TIMEOUT: "4000"
      FULLNODE_BASE_URL:
      JSON_RPC_TOKEN:
      GLOBAL_BLOCKBOOK_ENDPOINT:
      COIN_NAME:
      SENTRY_DSN:
      SCOPE:
    network_mode: "host"
