version: '3.9'
services:
  app:
    image: phinixhq/bitcoinish-fullnode-exporter
    restart: unless-stopped
    environment: 
      REFRESH_INTERVAL_MILLISECONDS: "60000"
      BITCOINISH_FULLNODE_BASE_URL:
      JSON_RPC_TOKEN:
      BITCOINISH_SCAN_BASE_URL:
      COIN_NAME:
    ports:
      - "9099:9099"
